# A composition of services that are needed to run the tests of the client
# This is for DEVELOPMENT, not production

version: "3"
services:
  alchemy:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - alchemy-server
      - graph-node
    working_dir: /alchemy/
    volumes:
      # - .:/alchemy
      - ./src:/alchemy/src
      - ./scripts:/alchemy/scripts
      - ./test:/alchemy/test
      - ./package.json:/alchemy/package.json
      - ./package-lock.json:/alchemy/package-lock.json
      - ./webpack.base.config.js:/alchemy/webpack.base.config.js
      - ./app.json:/alchemy/app.json
      - ./webpack.dev.config.js:/alchemy/webpack.dev.config.js
      - ./webpack.docker.config.js:/alchemy/webpack.docker.config.js
      - ./entry.sh:/entry.sh
      - ./config:/alchemy/config
    ports:
      - 3000:3000

  alchemy-server:
    build:
      context: ./docker/alchemy-server
    links:
      - postgres
    ports:
      - 3001:3001
    working_dir: /alchemy-server/
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    build:
      context: ./docker/postgres/
    # ports:
      # - 5435:5432

  graph-node:
    image: graphprotocol/graph-node:latest@sha256:bc64577f8ed7d2a7badb575d85d99bf017bdddd68bf20b032c184654d27a4bef
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres4graphnode
      - ganache
    environment:
      postgres_host: postgres4graphnode:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: development:http://ganache:8545
      GRAPH_LOG: "graph.log"

  ipfs:
    build:
      context: ./docker/ipfs/
    ports:
      - 5001:5001

  postgres4graphnode:
    image: postgres
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: daostack/migration:0.0.1-rc.11-v1
    ports:
      - 8545:8545
    command: >
      --gasLimit 8000000
